# Generated by Django 5.0.3 on 2024-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
