# Generated by Django 4.2 on 2024-12-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_reviewrating_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catg_description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catg_image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catg_name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rateing',
            field=models.IntegerField(),
        ),
    ]
