# Generated by Django 4.2 on 2024-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_rename_catg_description_category_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancel', 'cancel'), ('completed', 'completed')], default='pending', max_length=100),
        ),
    ]
