# Generated by Django 4.2 on 2025-01-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_cart_user_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='trending',
        ),
    ]
