# Generated by Django 4.2 on 2025-01-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_remove_category_status_remove_category_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
