# Generated by Django 4.2 on 2025-02-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_product_num_panels_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
