# Generated by Django 4.2 on 2024-11-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Phone_no', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('CNIC', models.CharField(max_length=35, unique=True)),
                ('Password', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
