# Generated by Django 4.2 on 2025-01-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0002_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Phone_no', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(default='', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
