# Generated by Django 4.2 on 2025-01-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
