# Generated by Django 4.2 on 2025-01-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_userdata_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='Phone_no',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='Name',
            new_name='first_name',
        ),
    ]
