# Generated by Django 4.2 on 2025-01-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
